### ISSUE TITLE
Upgrade Node to v14 or v16

### ISSUE THREAD

**Issue by chrismlusk** [Accuraty/AccuTheme-2021#15]
https://nodejs.org/en/about/releases/

v12 is no longer the active version. v14 is active, but transitions to maintenance in October. It's probably worth upgrading to v16 now. 

Another reason to update: A few pending NPM package upgrades for this project no longer support v12.

**Comment by jeremy-farrance** [comment]
Not sure I know enough to do this, but gave it a try. Can you take a look when you have a min? I got a clean setup of AccuTheme on my machine. Already upgraded to Node 14.17 LTS , new branch, upgraded Boostrap to ^4.6.0. Couldn't find anything else that seemed worth upgrading. Did install and build then copied the result up to ACCU4 as the default theme. Seems to be working well.
[https://accu4.com/](https://accu4.com/)

**Comment by jeremy-farrance** [comment]
I did not notice your commits from this morning, I now see that you updated dozens of dependencies. I did have those changes in place before I started. So... not sure what else we need to do here?

**Comment by chrismlusk** [comment]
Looks like a few of our build dependencies aren't ready for Node v14 at the moment. We'll revisit this later.
